package com.almica.mapsforge_compose.externalData

/**
 * 10sep2026
 * not needed in this app, but kept for ramani app
 */
class MagentaCloudMvt {
    companion object {
        val germany_north: Map<String, String> =
            mapOf(
                Pair("mvt_260_194_9.mbtiles", "https://magentacloud.de/public.php/dav/files/JD2AsCAf5r8S39R"),
                Pair("mvt_263_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/sK5pygKfdiG8C8r"),
                Pair("mvt_264_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/pe33BYcaowdjFyp"),
                Pair("mvt_264_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/WfB8iTbLWD9pkrf"),
                Pair("mvt_265_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/zfxPMLXkzLrJgbH"),
                Pair("mvt_265_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/Z9F48TmPoJLQLNj"),
                Pair("mvt_266_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/4sBM37K9tSyNe89"),
                Pair("mvt_266_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/FYzjawyEabLC6wR"),
                Pair("mvt_266_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/pRSFxyEo3JZtnH6"),
                Pair("mvt_266_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/rJdop8ot9AafPFH"),
                Pair("mvt_266_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/ggNKSwp5jcHoLJs"),
                Pair("mvt_266_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/rjsPki5AADi6aTd"),
                Pair("mvt_267_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/dxbAsE7ZZefR8Ps"),
                Pair("mvt_267_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/e3ow7CiPJw2dXox"),
                Pair("mvt_267_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/iJ8sxBf2mJF8We5"),
                Pair("mvt_267_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/fkr54xjDX8N23CF"),
                Pair("mvt_267_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/YzJ8FoptbCLr4WS"),
                Pair("mvt_267_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/7CJiomzp45XfzYb"),
                Pair("mvt_268_162_9.mbtiles", "https://magentacloud.de/public.php/dav/files/YTMkzDidZJNscCS"),
                Pair("mvt_268_163_9.mbtiles", "https://magentacloud.de/public.php/dav/files/Ka6Rbjd6grjCr9H"),
                Pair("mvt_268_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/Hi6nHBBBZRZ29L6"),
                Pair("mvt_268_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/cSDcZ6HenT8HN2e"),
                Pair("mvt_268_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/GbSgZiscd2qWZfP"),
                Pair("mvt_268_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/Npf4xTsmmrEwSKF"),
                Pair("mvt_268_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/LZbrnArkfWADZgr"),
                Pair("mvt_268_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/wxg3X2dF3D7YdCg"),
                Pair("mvt_268_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/KddnC85kQQ5nwrW"),
                Pair("mvt_269_162_9.mbtiles", "https://magentacloud.de/public.php/dav/files/pksmnNpiiy2Dfyr"),
                Pair("mvt_269_163_9.mbtiles", "https://magentacloud.de/public.php/dav/files/Rs49NZkHyFAxZsf"),
                Pair("mvt_269_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/aRw7tbxJLY95XZe"),
                Pair("mvt_269_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/kXNQq5rrtf5zoHn"),
                Pair("mvt_269_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/orNnDBTjbXdb9Qk"),
                Pair("mvt_269_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/4sJ3qn8ATfTWFRX"),
                Pair("mvt_269_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/CZsCkXoqZYX8LGt"),
                Pair("mvt_269_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/SCdKKaZ3dd75seA"),
                Pair("mvt_269_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/kgJ8W9pXYZjmMCK"),
                Pair("mvt_270_162_9.mbtiles", "https://magentacloud.de/public.php/dav/files/jDAyjSf6JZdcjEB"),
                Pair("mvt_270_163_9.mbtiles", "https://magentacloud.de/public.php/dav/files/m9Ma26jpzK5LZpa"),
                Pair("mvt_270_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/9aPNCEPtNR7kxTq"),
                Pair("mvt_270_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/prEGNf4XypCS9Zk"),
                Pair("mvt_270_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/Wo4bicxgnay9Wa5"),
                Pair("mvt_270_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/2ZRzmLiS3WZ7MKq"),
                Pair("mvt_270_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/EGRj4XQd2aF62Wn"),
                Pair("mvt_270_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/c2jL4gTx7XT285q"),
                Pair("mvt_270_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/nfcrGwCqEFnywY9"),
                Pair("mvt_271_163_9.mbtiles", "https://magentacloud.de/public.php/dav/files/tBRZacaFWLNyTi5"),
                Pair("mvt_271_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/oGRcdasWneZCdN3"),
                Pair("mvt_271_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/BktMTMmRbPCW69L"),
                Pair("mvt_271_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/ZsSLQ7bL5yCeJmS"),
                Pair("mvt_271_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/5SmrMQDMnebR3wK"),
                Pair("mvt_271_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/LmQ3cLPNY2FJnWg"),
                Pair("mvt_271_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/iHQqDjQTFjbqHzD"),
                Pair("mvt_271_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/sjX3rQxAsbSYrHz"),
                Pair("mvt_272_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/ToGBEXYbFa7N7m4"),
                Pair("mvt_272_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/GTK6FmABQqabpgp"),
                Pair("mvt_272_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/jTcmjdJFKkdqHzA"),
                Pair("mvt_272_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/6X9wdQ9n32CJ9Tz"),
                Pair("mvt_272_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/tJ3sM5BxYwCDPHi"),
                Pair("mvt_272_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/W4kSL5dP7QxprfZ"),
                Pair("mvt_272_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/DNkEbGitXso4sYo"),
                Pair("mvt_273_163_9.mbtiles", "https://magentacloud.de/public.php/dav/files/HA9cwHkqrJ4EngY"),
                Pair("mvt_273_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/wiq39aQrHxzG7Z7"),
                Pair("mvt_273_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/4zoRW6DeodcGSCb"),
                Pair("mvt_273_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/mgeYXTdQ2xWYgqf"),
                Pair("mvt_273_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/HSxSyrfDjHzJfyn"),
                Pair("mvt_273_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/M9FrpT4JDaGNWAD"),
                Pair("mvt_273_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/yKgZ25EkPDKqedm"),
                Pair("mvt_273_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/AWLJFzD26ZdZkTe"),
                Pair("mvt_274_162_9.mbtiles", "https://magentacloud.de/public.php/dav/files/5q7GfzseHqcanRC"),
                Pair("mvt_274_163_9.mbtiles", "https://magentacloud.de/public.php/dav/files/wAjQCGsrTHwtZRr"),
                Pair("mvt_274_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/sTZADwYfPo7QnQn"),
                Pair("mvt_274_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/mbRzsJsygp7oWiC"),
                Pair("mvt_274_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/z49ytntQLYjCsw6"),
                Pair("mvt_274_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/9Efi3mpy99ZNqTi"),
                Pair("mvt_274_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/kSwpW6NMG6bmj5t"),
                Pair("mvt_274_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/SjdXYM2RBZrFnXb"),
                Pair("mvt_274_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/8Hb6FBSJfkX2CY5"),
                Pair("mvt_275_163_9.mbtiles", "https://magentacloud.de/public.php/dav/files/EXEGFPy49kGoqk4"),
                Pair("mvt_275_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/5TcmQKsiBfC3fXN"),
                Pair("mvt_275_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/WyF3GTtFyEXeQMS"),
                Pair("mvt_275_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/9TBDDtG2zRYmdaE"),
                Pair("mvt_275_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/aJJ3bZW8HjEQa7C"),
                Pair("mvt_275_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/LLbbJN5LJrAcPJM"),
                Pair("mvt_275_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/WWzEkqn8TR4BjHz"),
                Pair("mvt_275_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/BkRZkp3545sy55q"),
                Pair("mvt_276_164_9.mbtiles", "https://magentacloud.de/public.php/dav/files/oKMS6ziBDqsr3Sz"),
                Pair("mvt_276_165_9.mbtiles", "https://magentacloud.de/public.php/dav/files/HK2x9p6RfbSTNgS"),
                Pair("mvt_276_166_9.mbtiles", "https://magentacloud.de/public.php/dav/files/YemGRcEdeBXfHDL"),
                Pair("mvt_276_167_9.mbtiles", "https://magentacloud.de/public.php/dav/files/rxweewcw8aSL7mw"),
                Pair("mvt_276_168_9.mbtiles", "https://magentacloud.de/public.php/dav/files/9fBiGioiWNoyKtD"),
                Pair("mvt_276_169_9.mbtiles", "https://magentacloud.de/public.php/dav/files/8m6D4859SP5XiGA"),
                Pair("mvt_276_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/4fML73NBQJ2drHe"),
                Pair("mvt_277_170_9.mbtiles", "https://magentacloud.de/public.php/dav/files/LmpqMotYasEgGBK"),
                Pair("planet.mbtiles", "https://magentacloud.de/public.php/dav/files/de2JX7rqxopDRza")
            )
    }
}